// vue/vue2/vue2base/src/App.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: OpenLcuk
 * @Date: 2021-10-13 16:20:53
 * @LastEditors: OpenLcuk
 * @LastEditTime: 2021-11-12 17:08:54
-->
<template>
  <div id="app">
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: "App",
  components: {},
  data() {
    return {};
  },
  created() {
    console.log("process", process);
  },
};
</script>

<style>
</style>

// react/react-ts-web-shop/src/App.tsx
/*
 * @Descripttion:
 * @version:
 * @Author: OpenLcuk
 * @Date: 2021-10-15 10:17:39
 * @LastEditors: OpenLcuk
 * @LastEditTime: 2021-10-15 16:02:58
 */
import React from "react";
import logo from "./logo.svg";
import "./App.css";
// 引入组件
import { Header } from "./components/header";

function App() {
  return (
    <div className="App">
      <Header></Header>
    </div>
  );
}

export default App;
