// react/react-base/src/App.js
/*
 * @Descripttion: 
 * @version: 
 * @Author: OpenLcuk
 * @Date: 2021-10-15 14:45:52
 * @LastEditors: OpenLcuk
 * @LastEditTime: 2021-10-15 14:57:57
 */
import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        test
      </header>
    </div>
  );
}

export default App;

// vue/vue2/vue2base/src/App.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: OpenLcuk
 * @Date: 2021-10-13 16:20:53
 * @LastEditors: OpenLcuk
 * @LastEditTime: 2021-11-12 17:08:54
-->
<template>
  <div id="app">
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: "App",
  components: {},
  data() {
    return {};
  },
  created() {
    console.log("process", process);
  },
};
</script>

<style>
</style>
