// vue/vue2/vue2base/src/App.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: OpenLcuk
 * @Date: 2021-10-13 16:20:53
 * @LastEditors: OpenLcuk
 * @LastEditTime: 2021-11-12 17:08:54
-->
<template>
  <div id="app">
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: "App",
  components: {},
  data() {
    return {};
  },
  created() {
    console.log("process", process);
  },
};
</script>

<style>
</style>

// project/news/news-react-ts/src/App.tsx
/*
 * @Descripttion:
 * @version:
 * @Author: OpenLcuk
 * @Date: 2021-10-21 13:37:01
 * @LastEditors: OpenLcuk
 * @LastEditTime: 2021-11-18 17:13:49
 */
import React, { FC } from "react";
import { BrowserRouter as Router, Routes,Route } from 'react-router-dom';
import Login from "../src/pages/login";

const App: FC = () => (
  <Router>
    <Routes>
      <Route path="/" element={<Login />} />
    </Routes>
  </Router>
);

export default App;
