// vue/vue2/vue2base/src/layouts/Header.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: OpenLcuk
 * @Date: 2021-11-12 15:07:42
 * @LastEditors: OpenLcuk
 * @LastEditTime: 2021-11-16 16:49:31
-->
<template>
  <div class="header">
    <p>this's header</p>
  </div>
</template>

<script>
export default {
  name: '',
  data() { 
    return {

    }
  },
  
 }
</script>

<style lang="" scoped>
</style>

// react/react-ts-web-shop/src/components/header.tsx
/*
 * @Descripttion:
 * @version:
 * @Author: OpenLcuk
 * @Date: 2021-10-15 15:52:03
 * @LastEditors: OpenLcuk
 * @LastEditTime: 2021-10-15 16:52:26
 */
import React from "react";

// interface
export const Header = () => {
  return (
    <div>
      <div
        style={{
          height: "30px",
          background: "#000",
          color: "#fff",
        }}
      >
        这是头部
      </div>
    </div>
  );
};

// import React, { useState } from "react";

// export default function Button() {
//   const [buttonText, setButtonText] = useState("Click me,   please");

//   function handleClick() {
//     return setButtonText("Thanks, been clicked!");
//   }

//   return <button onClick={handleClick}>{buttonText}</button>;
// }
